# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_comparacao.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Comparacao(object):
    def setupUi(self, Tela_Comparacao):
        Tela_Comparacao.setObjectName("Tela_Comparacao")
        Tela_Comparacao.resize(1276, 585)
        Tela_Comparacao.setFixedSize(1276, 585)
        self.centralwidget = QtWidgets.QWidget(Tela_Comparacao)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_abrir_arquivo1 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_abrir_arquivo1.setGeometry(QtCore.QRect(10, 410, 121, 27))
        self.botao_abrir_arquivo1.setObjectName("botao_abrir_arquivo1")
        self.botao_abrir_arquivo2 = QtWidgets.QPushButton(self.centralwidget)
        self.botao_abrir_arquivo2.setGeometry(QtCore.QRect(650, 410, 121, 27))
        self.botao_abrir_arquivo2.setObjectName("botao_abrir_arquivo2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 150, 101, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 150, 101, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 80, 171, 17))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(420, 80, 85, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 80, 61, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 80, 81, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(800, 80, 41, 17))
        self.label_6.setObjectName("label_6")
        self.match = QtWidgets.QLineEdit(self.centralwidget)
        self.match.setGeometry(QtCore.QRect(590, 80, 41, 27))
        self.match.setObjectName("match")
        self.mismatch = QtWidgets.QLineEdit(self.centralwidget)
        self.mismatch.setGeometry(QtCore.QRect(740, 80, 41, 27))
        self.mismatch.setObjectName("mismatch")
        self.gap = QtWidgets.QLineEdit(self.centralwidget)
        self.gap.setGeometry(QtCore.QRect(840, 80, 41, 27))
        self.gap.setObjectName("gap")
        self.botao_realizar_comparacao = QtWidgets.QPushButton(self.centralwidget)
        self.botao_realizar_comparacao.setGeometry(QtCore.QRect(540, 480, 181, 71))
        self.botao_realizar_comparacao.setObjectName("botao_realizar_comparacao")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 50, 1276, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(10, 10, 99, 27))
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap("images/voltar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.botao_voltar.setIcon(icon)
        self.botao_voltar.setObjectName("botao_voltar")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(200, 50, 1276, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.setar_sequencia1 = QtWidgets.QTextEdit(self.centralwidget)
        self.setar_sequencia1.setGeometry(QtCore.QRect(10, 180, 611, 221))
        self.setar_sequencia1.setReadOnly(True)
        self.setar_sequencia1.setObjectName("setar_sequencia1")
        self.setar_sequencia2 = QtWidgets.QTextEdit(self.centralwidget)
        self.setar_sequencia2.setGeometry(QtCore.QRect(650, 180, 611, 221))
        self.setar_sequencia2.setReadOnly(True)
        self.setar_sequencia2.setObjectName("setar_sequencia2")
        Tela_Comparacao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Tela_Comparacao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1276, 25))
        self.menubar.setObjectName("menubar")
        Tela_Comparacao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Tela_Comparacao)
        self.statusbar.setObjectName("statusbar")
        Tela_Comparacao.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_Comparacao)
        QtCore.QMetaObject.connectSlotsByName(Tela_Comparacao)

    def retranslateUi(self, Tela_Comparacao):
        _translate = QtCore.QCoreApplication.translate
        Tela_Comparacao.setWindowTitle(_translate("Tela_Comparacao", "Tela de Comparação"))
        self.botao_abrir_arquivo1.setText(_translate("Tela_Comparacao", "ABRIR ARQUIVO"))
        self.botao_abrir_arquivo2.setText(_translate("Tela_Comparacao", "ABRIR ARQUIVO"))
        self.label.setText(_translate("Tela_Comparacao", "SEQUÊNCIA 1:"))
        self.label_2.setText(_translate("Tela_Comparacao", "SEQUÊNCIA 2:"))
        self.label_3.setText(_translate("Tela_Comparacao", "TIPO DE COMPARAÇÃO:"))
        self.comboBox.setItemText(0, _translate("Tela_Comparacao", "GLOBAL"))
        self.comboBox.setItemText(1, _translate("Tela_Comparacao", "LOCAL"))
        self.label_4.setText(_translate("Tela_Comparacao", "MATCH:"))
        self.label_5.setText(_translate("Tela_Comparacao", "MISMATCH:"))
        self.label_6.setText(_translate("Tela_Comparacao", "GAP:"))
        self.botao_realizar_comparacao.setText(_translate("Tela_Comparacao", "REALIZAR COMPARAÇÃO"))
        self.botao_voltar.setText(_translate("Tela_Comparacao", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Comparacao = QtWidgets.QMainWindow()
    ui = Ui_Tela_Comparacao()
    ui.setupUi(Tela_Comparacao)
    Tela_Comparacao.show()
    sys.exit(app.exec_())
