# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_Tela_Principal(object):
    def setupUi(self, Tela_Principal):
        Tela_Principal.setObjectName("Tela_Principal")
        Tela_Principal.setWindowModality(Qt.NonModal)
        Tela_Principal.resize(1000, 600)
        Tela_Principal.setAutoFillBackground(False)
        Tela_Principal.setToolButtonStyle(Qt.ToolButtonIconOnly)
        Tela_Principal.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(Tela_Principal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QLabel(self.centralwidget)
        self.label.setFrameShape(QFrame.Box)
        self.label.setFrameShadow(QFrame.Sunken)
        self.label.setLineWidth(4)
        self.label.setMidLineWidth(0)
        self.label.setTextFormat(Qt.AutoText)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QFrame(self.centralwidget)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.botao_tela_comparacao = QPushButton(self.centralwidget)
        self.botao_tela_comparacao.setCursor(QCursor(Qt.PointingHandCursor))
        self.botao_tela_comparacao.setObjectName("botao_tela_comparacao")
        self.verticalLayout_2.addWidget(self.botao_tela_comparacao)
        spacerItem = QSpacerItem(20, 13, QSizePolicy.Minimum, QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem)
        self.botao_tela_converter = QPushButton(self.centralwidget)
        self.botao_tela_converter.setCursor(QCursor(Qt.PointingHandCursor))
        self.botao_tela_converter.setObjectName("botao_tela_converter")
        self.verticalLayout_2.addWidget(self.botao_tela_converter)
        spacerItem1 = QSpacerItem(20, 13, QSizePolicy.Minimum, QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.botao_tela_outras = QPushButton(self.centralwidget)
        self.botao_tela_outras.setCursor(QCursor(Qt.PointingHandCursor))
        self.botao_tela_outras.setObjectName("botao_tela_outras")
        self.verticalLayout_2.addWidget(self.botao_tela_outras)
        spacerItem2 = QSpacerItem(20, 13, QSizePolicy.Minimum, QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.botao_tela_outras_2 = QPushButton(self.centralwidget)
        self.botao_tela_outras_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.botao_tela_outras_2.setObjectName("botao_tela_outras_2")
        self.verticalLayout_2.addWidget(self.botao_tela_outras_2)
        spacerItem3 = QSpacerItem(20, 13, QSizePolicy.Minimum, QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.botao_sair = QPushButton(self.centralwidget)
        self.botao_sair.setCursor(QCursor(Qt.PointingHandCursor))
        self.botao_sair.setAutoDefault(False)
        self.botao_sair.setDefault(False)
        self.botao_sair.setFlat(False)
        self.botao_sair.setObjectName("botao_sair")
        self.verticalLayout_2.addWidget(self.botao_sair)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        Tela_Principal.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Tela_Principal)
        self.statusbar.setObjectName("statusbar")
        Tela_Principal.setStatusBar(self.statusbar)

        self.retranslateUi(Tela_Principal)
        QMetaObject.connectSlotsByName(Tela_Principal)

    def retranslateUi(self, Tela_Principal):
        _translate = QCoreApplication.translate
        Tela_Principal.setWindowTitle(_translate("Tela_Principal", "Tela Inicial - GeMapCom"))
        self.label.setText(_translate("Tela_Principal", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600;\">GeMapCom</span></p></body></html>"))
        self.botao_tela_comparacao.setText(_translate("Tela_Principal", "COMPARAR SEQUENCIAS"))
        self.botao_tela_converter.setText(_translate("Tela_Principal", "CONVERTER SEQUENCIA"))
        self.botao_tela_outras.setText(_translate("Tela_Principal", "BLAST+"))
        self.botao_tela_outras_2.setText(_translate("Tela_Principal", "OUTRAS FERRAMENTAS"))
        self.botao_sair.setText(_translate("Tela_Principal", "SAIR"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Tela_Principal = QMainWindow()
    ui = Ui_Tela_Principal()
    ui.setupUi(Tela_Principal)
    Tela_Principal.show()
    sys.exit(app.exec_())
